[package]
name = "vkgen"
version = "0.1.0"
authors = ["Usman Zahid <usmanzahid1998@gmail.com>"]
edition = "2021"

[dependencies]
roxmltree = "0.18"

[profile.dev]
opt-level = 1

[profile.release]
lto = "fat"
